/// <reference types="cypress" />

describe('Actions', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/?name=&date=&time=&number=')
  })

  it('should load the home page', () => {
    cy.get('.app-title')
      .contains('Turing Cafe Reservations')
      .get('form').children('input')
      .should('have.class', 'name-input')
      .should('have.class', 'date-input')
      .should('have.class', 'time-input')
      .should('have.class', 'number-input')
      .get('button')
      .should('have.class', 'submit-button')
    cy.get('.resy-container')
      .children('div')
      .should('have.class', 'resy')
  })
  
  it('should show data as it is entered into the form', () => {
    cy.get('.resy-form').children().first()
      .focus('.name-input')
      .should('have.value', '')
      .type('lovely leta')
      .should('have.value', 'lovely leta')
      .next().focus('date-input')
      .should('have.value', '')
      .type('2021-05-28')
      .should('have.value', '2021-05-28')
      .next().focus('time-input')
      .should('have.value', '')
      .type('10:45')
      .should('have.value', '10:45')
      .next().focus('number-input')
      .should('have.value', '')
      .type('4')
      .should('have.value', '4')
      .next()
      .should('have.class', 'submit-button')
      .click()
  })

  it('should show new reservation when button is clicked', () => {
    cy.get('.resy-form').children().first()
      .focus('.name-input')
      .type('super scott')
      .next().focus('date-input')
      .type('2021-04-01')
      .next().focus('time-input')
      .type('01:23')
      .next().focus('number-input')
      .type('5')
      .next().should('have.class', 'submit-button')
      .click()
    cy.get('.resy-container').children()
      .get('p:last')
      .contains('5')
      .prev()
      .contains('01:23')
      .prev()
      .contains('2021-04-01')
      .prev()
      .contains('super scott')
  })
})
